#567 FloorPlanController에서 floorId와 latest값에 따라 해당하는 floorPlan 레코드값 읽어오는 로직 추가
hancom-io/hanzari pull request #572
Opened 2020-11-10 06:59 UTC by DongminKim94

2020-11-10 07:08 UTC, AhnHyeonho requested changes
전반적으로 logger를 이용하는 방법으로 수정해보세요

2020-11-10 07:08 UTC, AhnHyeonho commented on HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/FloorPlanController.java
> +	private String getFloorPlanFileName;
StringBuffer, StringBuilder에 대해 찾아보고 String 형태말고 다른 형태도 생각해보면 좋을 것 같습니다.

2020-11-10 07:08 UTC, AhnHyeonho commented on HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/FloorPlanController.java
> +			System.out.println("Can't put object in the MinIO bucket / " + e);
로그를 위한거라면 console이 아닌 logger를 통해 남기면 좋을 것 같습니다.

2020-11-10 07:08 UTC, AhnHyeonho commented on HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/FloorPlanController.java
>  			e.printStackTrace();
이런 부분도 logger를 통해 exception이 발생한 경우를 기록으로 남기는 게 좋을 것 같습니다.

2020-11-10 07:08 UTC, AhnHyeonho commented on HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/FloorPlanController.java
> +			System.out.println("Can't get object from the MinIO bucket / " + e);
마찬가지로 이 부분도 logger를 통해 exception이 발생한 경우를 기록으로 남기는 게 좋을 것 같습니다.

2020-11-11 01:52 UTC, DongminKim94 commented on HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/FloorPlanController.java
> +	private String getFloorPlanFileName;
String이 아닌 StringBuffer를 사용하여 메모리 낭비가 일어날 수 있는 상황을 대비하고 멀티 쓰레드 환경을 고려하도록 했습니다.

2020-11-11 01:53 UTC, DongminKim94 commented on HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/FloorPlanController.java
> +			System.out.println("Can't put object in the MinIO bucket / " + e);
logger.error를 사용하는 방식으로 변경을 하였고 해당 메소드 호출을 알리기 위한 logger.info도 메소드 시작점에 추가해주었습니다.

2020-11-11 01:53 UTC, DongminKim94 commented on HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/FloorPlanController.java
>  			e.printStackTrace();
동일하게 변경하였습니다.

2020-11-11 01:53 UTC, DongminKim94 commented on HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/FloorPlanController.java
> +			System.out.println("Can't get object from the MinIO bucket / " + e);
동일하게 변경하였습니다. 상세한 리뷰 감사합니다. 👍

2020-11-11 02:07 UTC, AhnHyeonho requested changes

2020-11-11 02:07 UTC, AhnHyeonho commented on HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/FloorPlanController.java
>  			e.printStackTrace();
이 부분은 아직 logger가 달리지 않았네요! 이부분만 추가해주시면 될 것 같습니다.

2020-11-11 02:15 UTC, DongminKim94 commented on HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/FloorPlanController.java
>  			e.printStackTrace();
8c5baa6 추가했습니다~! 👍

2020-11-11 02:17 UTC, AhnHyeonho approved these changes
LGTM 👏👏👏

2020-11-11 02:18 UTC, merged