#581 이미지 파일 정보가 데이터베이스에 저장 안되던 문제 해결(이전 버전의 프론트엔드 코드로 테스트를 하여서 에러가 났었음.)
hancom-io/hanzari pull request #615
Opened 2020-11-12 04:33 UTC by DongminKim94

2020-11-12 04:43 UTC, AhnHyeonho requested changes

2020-11-12 04:43 UTC, AhnHyeonho commented on HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/FloorPlanController.java
> +		LOGGER.info("Image File name change to {} for store in MinIO bucket", putFloorPlanFileName);
putFloorPlanFileName.toString()으로 바꿔주세요

2020-11-12 04:43 UTC, AhnHyeonho commented on HanzariProject/backend/src/main/java/com/hancom/hanzari/model/Floor.java
> +	//private int floorImageUrl;
지금 당장 사용하지않기때문에 주석처리한거라면 주석을 친 이유를 같이 남겨주면 좋을 것 같습니다.
만약 정리가 되지 않은 주석이라면 지워주세요!

2020-11-12 04:43 UTC, AhnHyeonho commented on HanzariProject/backend/src/main/java/com/hancom/hanzari/model/Floor.java
> +	//private FloorPlan floorPlan;
지금 당장 사용하지않기때문에 주석처리한거라면 주석을 친 이유를 같이 남겨주면 좋을 것 같습니다.
만약 정리가 되지 않은 주석이라면 지워주세요!

2020-11-12 04:43 UTC, AhnHyeonho commented on HanzariProject/backend/src/main/java/com/hancom/hanzari/model/FloorPlan.java
> +	private Boolean latest;
@NotNull로 줄거라면 boolean형으로 줘도 괜찮을 것 같습니다.
Boolean : nullable (Reference type)
boolean : not nullable (primitive type)

[참고자료](https://stackoverflow.com/questions/1295170/whats-the-difference-between-boolean-and-boolean-in-java)

2020-11-12 04:43 UTC, AhnHyeonho commented on HanzariProject/backend/src/main/java/com/hancom/hanzari/model/FloorPlan.java
> +	//private Floor floor;
지금 당장 사용하지않기때문에 주석처리한거라면 주석을 친 이유를 같이 남겨주면 좋을 것 같습니다.
만약 정리가 되지 않은 주석이라면 지워주세요!

2020-11-12 04:43 UTC, AhnHyeonho commented on HanzariProject/backend/src/main/java/com/hancom/hanzari/service/FloorPlanServiceImpl.java
> +//	}
지금 당장 사용하지않기때문에 주석처리한거라면 주석을 친 이유를 같이 남겨주면 좋을 것 같습니다.
만약 정리가 되지 않은 주석이라면 지워주세요!

2020-11-12 04:54 UTC, DongminKim94 commented on HanzariProject/backend/src/main/java/com/hancom/hanzari/model/FloorPlan.java
> +	private Boolean latest;
저는 DB 데이터형을 기준으로 생각하여 자료를 찾아보았고 자바의 Boolean 타입과 DB의 bit(1) 타입이 매칭된다하여 Boolean으로 작성을 하였습니다. Boolean 타입이 null이 들어갈 수 있다는 것은 몰랐군요. 더불어 @NotNull 어노테이션과도 논리적으로 맞지 않네요. boolean과 bit(1)이 매칭되어 잘 돌아간다면 boolean으로 주는 것이 좋겠네요.

2020-11-12 04:56 UTC, DongminKim94 commented on HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/FloorPlanController.java
> +		LOGGER.info("Image File name change to {} for store in MinIO bucket", putFloorPlanFileName);
오 꼼꼼한 리뷰 감사해요. 👍

2020-11-12 05:11 UTC, DongminKim94 commented on HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/FloorPlanController.java
> +		LOGGER.info("Image File name change to {} for store in MinIO bucket", putFloorPlanFileName);
73f0612 수정하였습니다.

2020-11-12 05:11 UTC, DongminKim94 commented on HanzariProject/backend/src/main/java/com/hancom/hanzari/model/Floor.java
> +	//private int floorImageUrl;
4e536eb 수정하였습니다.

2020-11-12 05:12 UTC, DongminKim94 commented on HanzariProject/backend/src/main/java/com/hancom/hanzari/model/Floor.java
> +	//private FloorPlan floorPlan;
9b298e2 수정하였습니다.

2020-11-12 05:12 UTC, DongminKim94 commented on HanzariProject/backend/src/main/java/com/hancom/hanzari/model/FloorPlan.java
> +	//private Floor floor;
c0cded5 수정하였습니다.

2020-11-12 05:13 UTC, DongminKim94 commented on HanzariProject/backend/src/main/java/com/hancom/hanzari/service/FloorPlanServiceImpl.java
> +//	}
0033e47 수정하였습니다.

2020-11-12 05:35 UTC, AhnHyeonho approved these changes
VERY GOOOOOD 👏👏🙌

2020-11-12 05:40 UTC, merged

2020-11-13 07:40 UTC, hnc-cjcho commented on HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/FloorPlanController.java
> +		LOGGER.info("Image File name change to {} for store in MinIO bucket", putFloorPlanFileName);
@AhnHyeonho // 혹시 꼭 toString()을 붙여 줄 필요가 있는건가요?

2020-11-13 07:45 UTC, DongminKim94 commented on HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/FloorPlanController.java
> +		LOGGER.info("Image File name change to {} for store in MinIO bucket", putFloorPlanFileName);
@hnc-cjcho 다양하게 오버로딩 된 LOGGER의 info 메소드들이 있지만 지금 프로젝트 내에서 info 메소드를 사용할 때에는 두번째 인자를 전부 string 타입으로 넘겨 통일성을 주고자 해당 변수도 string으로 변환을 하였습니다.

2020-11-13 07:49 UTC, hnc-cjcho commented on HanzariProject/backend/src/main/java/com/hancom/hanzari/controllers/FloorPlanController.java
> +		LOGGER.info("Image File name change to {} for store in MinIO bucket", putFloorPlanFileName);
현재 상태라면, putFloorPlanFileName의 toString()을 무조건 호출하게 되어 있습니다.
만약 서버의 상태가 Info level의 log를 찍지 않는것으로 설정을 해 두었다면, 
로그를 찍지도 않을 객체의 toString()을 호출한것이 됩니다.
무언가 다른 이유가 있다면 알려 주세요~